# Generated by Django 5.1.6 on 2025-02-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='dupr',
            field=models.FloatField(),
        ),
    ]
