# Generated by Django 5.1.5 on 2025-02-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(verbose_name='Game Date'),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.BooleanField(choices=[(True, 'I won this game!'), (False, 'I lost this game.')], default=(True, 'I won this game!')),
        ),
    ]
