# Generated by Django 5.1.5 on 2025-02-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_gear_alter_game_options_alter_game_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='gears',
            field=models.ManyToManyField(to='main_app.gear'),
        ),
    ]
